# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91fdd1098a8d4155f3e8e19868dff3b8157d24ff88386da89a73a651ad882cc4b49ed994f4391c9a2ee40da6e6c89dcbab848801ec88b1053d475882d9e4bee0
  facebook_app_id: 1656803974607188
  facebook_app_secret: caee44ec291ea24af7765b1f68d4c3ab


test:
  secret_key_base: 0c53c2a3c7637b5fa6161faa80b458f38187767e3085f06b283fac1a596a593f16382807ec933165aac97eacc0da7c66377fc8596f57b7c96a8cac19f01a201b
  facebook_app_id: 1656803974607188
  facebook_app_secret: caee44ec291ea24af7765b1f68d4c3ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 1656803974607188
  facebook_app_secret: <%= ENV["YELP_FACEBOOK_APP_SECRET"] %>
